### ISSUE TITLE
Docstring, readme, basic docs missing

### ISSUE THREAD

**Issue by bowentan** [bowentan/glob-linters#3]
Need to add the following:
- [x] docstring
- [x] README
- [x] CONTRIBUTING
- [x] docs/installation.rst
- [x] docs/usage.rst

**Comment by szabgab** [comment]
In the readme there is a link to https://glob-linters.readthedocs.io/ but that page does not exist.

**Comment by bowentan** [comment]
> In the readme there is a link to https://glob-linters.readthedocs.io/ but that page does not exist.

Yes, I only put that link online but have not filled the contents. I will fill that in this issue.
